services:
  mysql:
    container_name: mysql-sql-bsn
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_management_version_deploy
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.0
    ports:
      - 8080:8080
    networks:
      - spring-demo
    depends_on:
      - mysql
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql-data:
    driver: local
