version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  backend:
    build:
      context: ./spring-boot-3-jwt-security-main
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend2
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow root without password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:
